In [1]:
dataset = []
path = 'dataset1.txt'
f = open(path, 'r')
for line in f:
	dataset.append(line.split())
f.close()

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

           0      1     10    100   1000  ...   9995   9996   9997   9998   9999
0       True   True   True  False  False  ...  False  False  False  False  False
1      False  False  False  False  False  ...  False  False  False  False  False
2      False  False  False  False  False  ...  False  False  False  False  False
3      False  False  False  False  False  ...  False  False  False  False  False
4      False  False  False  False  False  ...  False  False  False  False  False
...      ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
88157  False  False  False  False  False  ...  False  False  False  False  False
88158  False  False  False  False  False  ...  False  False  False  False  False
88159  False  False  False  False  False  ...  False  False  False  False  False
88160  False  False  False  False  False  ...  False  False  False  False  False
88161  False  False  False  False  False  ...  False  False  False  False  False

[88162 rows x 16470 columns]

In [6]:
from mlxtend.frequent_patterns import apriori
import time

def apriori_sort(df, min_support, sort = "none"):
  start_time = time.time()
  dfa = apriori(df, min_support, use_colnames=True)
  if sort == "sup":
    print("Сортировка по support")
    dfa = dfa.sort_values(by=['support'])
  if sort == "items":
    print("Сортировка по itemsets")
    dfa = dfa.sort_values(by=['itemsets'])
  endtime  = time.time() - start_time
  return [dfa,endtime]

In [10]:
min_support = 0.01
sort = "none"
dfa_list = apriori_sort(df, min_support, sort)

print("Time of execution: ", dfa_list[1])
print("Min support: ", min_support)
dfa_list[0]

Time of execution:  45.45654511451721
Min support:  0.01

      support           itemsets
0    0.012500             (1004)
1    0.025374              (101)
2    0.010004            (10515)
3    0.031692              (110)
4    0.016175             (1146)
..        ...                ...
154  0.013532  (39, 48, 38, 170)
155  0.014020   (39, 48, 32, 38)
156  0.018670   (39, 48, 41, 32)
157  0.012250   (39, 48, 36, 38)
158  0.022583   (39, 48, 41, 38)

[159 rows x 2 columns]

In [11]:
min_support = 0.03
sort = "none"
dfa_list = apriori_sort(df, min_support, sort)

print("Time of execution: ", dfa_list[1])
print("Min support: ", min_support)
dfa_list[0]

Time of execution:  34.387046813964844
Min support:  0.03

     support      itemsets
0   0.031692         (110)
1   0.035151         (170)
2   0.036943         (225)
3   0.034391         (237)
4   0.172036          (32)
5   0.033302          (36)
6   0.176902          (38)
7   0.574794          (39)
8   0.169517          (41)
9   0.477927          (48)
10  0.050725          (65)
11  0.043522          (89)
12  0.030909     (110, 38)
13  0.034380     (170, 38)
14  0.032134      (32, 38)
15  0.095903      (39, 32)
16  0.036251      (41, 32)
17  0.091128      (48, 32)
18  0.031646      (36, 38)
19  0.117341      (39, 38)
20  0.044203      (41, 38)
21  0.090107      (48, 38)
22  0.129466      (39, 41)
23  0.330551      (39, 48)
24  0.031612      (65, 39)
25  0.031181      (89, 39)
26  0.102289      (48, 41)
27  0.031737      (89, 48)
28  0.061274  (39, 48, 32)
29  0.034607  (39, 41, 38)
30  0.069213  (39, 48, 38)
31  0.083551  (39, 48, 41)

In [12]:
min_support = 0.05
sort = "none"
dfa_list = apriori_sort(df, min_support, sort)

print("Time of execution: ", dfa_list[1])
print("Min support: ", min_support)
dfa_list[0]

Time of execution:  33.49255990982056
Min support:  0.05

     support      itemsets
0   0.172036          (32)
1   0.176902          (38)
2   0.574794          (39)
3   0.169517          (41)
4   0.477927          (48)
5   0.050725          (65)
6   0.095903      (39, 32)
7   0.091128      (48, 32)
8   0.117341      (39, 38)
9   0.090107      (48, 38)
10  0.129466      (39, 41)
11  0.330551      (39, 48)
12  0.102289      (48, 41)
13  0.061274  (39, 48, 32)
14  0.069213  (39, 48, 38)
15  0.083551  (39, 48, 41)

In [13]:
min_support = 0.1
sort = "none"
dfa_list = apriori_sort(df, min_support, sort)

print("Time of execution: ", dfa_list[1])
print("Min support: ", min_support)
dfa_list[0]

Time of execution:  33.77554965019226
Min support:  0.1

    support  itemsets
0  0.172036      (32)
1  0.176902      (38)
2  0.574794      (39)
3  0.169517      (41)
4  0.477927      (48)
5  0.117341  (39, 38)
6  0.129466  (39, 41)
7  0.330551  (39, 48)
8  0.102289  (48, 41)

In [14]:
min_support = 0.15
sort = "none"
dfa_list = apriori_sort(df, min_support, sort)

print("Time of execution: ", dfa_list[1])
print("Min support: ", min_support)
dfa_list[0]

Time of execution:  33.26016044616699
Min support:  0.15

    support  itemsets
0  0.172036      (32)
1  0.176902      (38)
2  0.574794      (39)
3  0.169517      (41)
4  0.477927      (48)
5  0.330551  (39, 48)